
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: titan-odin
  name: titan-odin
spec:
  containers:
    - image: anuragsarkar250/backend:1
      name: titan-odin
      env: 
      - name: "ETCD3_URL"
        value: "http://etcd-client:2379"
      ports:
      - containerPort: 5000
        name: titan-odin
        protocol: TCP
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: titan-odin
  name: titan-odin
spec:
  ports:
  - name: titan-odin
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: titan-odin
